# Workflow to Automatically Update Data Sources in the Repository
name: Automated Data Updates 

# Controls when the action will run. 
on:
  
  # Time-based workflow trigger (at 00:00, 08:00, 16:00)
  schedule:
    - cron: '0 0,8,16 * * *'  
    
# The job executed by the workflow
jobs:
  
  # This workflow contains a single job called "update_data_sources"
  update_data_sources:
    
    # This job runs on Linux using Python 3.7 version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # The sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
             
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/.github/workflows/requirements.txt
      
      - name: Configure Git Credentials
        run: |
          echo ${{ github.workspace }}
          git config --local user.email "action@agithub.com"
          git config --local user.name "GitHub Action"
        
      - name: Update JohnsHopkinsCSSE data
        run: |
          cd ${{ github.workspace }}/data/all_countries/JohnsHopkinsCSSE/
          echo Updating JohnsHopkinsCSSE source..
          python download.py
          cd ${{ github.workspace }}/data-processing/
          python extract_json.py
          python extract_json_greece.py
          
      - name: Update isMOOD data
        run: |
          cd ${{ github.workspace }}/data/greece/isMOOD/
          echo Updating isMOOD source..
          python download.py

      # - name: Update Wikipedia data
      #   run: |
      #     cd ${{ github.workspace }}/data/greece/wikipedia/
      #     echo Updating Wikipedia source..
      #     python webcrawler.py
      #     echo Done.

     - name: Update schools status data
       run: |
         cd ${{ github.workspace }}/data/greece/schools_status/
         echo Updating schools status source..
         python webcrawler.py
         echo Done.
      
      - name: Update regions data
        run: |
          cd ${{ github.workspace }}/data/greece/Regions/
          echo Updating regions source..
          python download.py
      
      - name: Update refugee camps data
        run: |
          cd ${{ github.workspace }}/data/greece/Refugee_camps/
          echo Updating refugee camps source..
          python download.py
          
      - name: Update iMEdD-Lab data
        run: |
          cd ${{ github.workspace }}
          cd data/greece/iMEdD-Lab/
          echo Updating iMEdD-Lab source..          
          python download.py
          
      - name: Append isMOOD daily data to timeline csv
        run: |
          cd ${{ github.workspace }}/data/greece/isMOOD/
          echo Appending isMOOD data to csv..
          python append_json_to_csv.py

      - name: Commit files
        run: |
          git add -A
          git commit -m "Automated Data Update using Workflows"
      
      - name: Push changes                               
        uses: ad-m/github-push-action@master
        with:                                 
         github_token: ${{ secrets.GITHUB_TOKEN }}
